DROP TABLE IF EXISTS speaker;

CREATE TABLE speaker(
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    subject VARCHAR(255),
    date DATE NOT NULL,
    words INTEGER,
    PRIMARY KEY (id)
);